print("***************** Start  program *************************")
print("Python is a popular programming language.")
print("Python can be used on a server to create web applications.")
print("Hello, world!")

print("What is Python?")
print("Python is a popular programming language. It was created by Guido van Rossum, and released in 1991.")
print("It is used for:")
print("web development (server-side),")
print("software development,")
print("mathematics,")
print("system scripting.")
print("What can Python do?")
print("Python can be used on a server to create web applications.")
print("Python can be used alongside software to create workflows.")
print("Python can connect to database systems. It can also read and modify files.")
print("Python can be used to handle big data and perform complex mathematics.")
print("Python can be used for rapid prototyping, or for production-ready software development.")
print("Why Python?")
print("Python works on different platforms (Windows, Mac, Linux, Raspberry Pi, etc).")
print("Python has a simple syntax similar to the English language.")
print("Python has syntax that allows developers to write programs with fewer lines than some other programming languages.")
print("Python runs on an interpreter system, meaning that code can be executed as soon as it is written. This means that prototyping can be very quick.")
print("Python can be treated in a procedural way, an object-oriented way or a functional way.")
print("***************** End program *************************")