# This is a basic workflow to help you get started with Actions
name: CI
# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - uses: jannekem/run-python-script-action@v1
      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!
      # Runs a set of commands using the runners shell
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install camelcase
      - name: Run a multi-line script
        run: |
          git config --global user.email "ag14341@gmail.com"
          git config --global user.name "ag143"
          echo Add other actions to build,
          echo test, and deploy your project.
          python -V
          python3 introduction.py >pythonoutput.md
          python3 array.py >> pythonoutput.md
          python3 camelcasetest.py >>pythonoutput.md
          python3 casting.py >>pythonoutput.md
          #python3 classobjects.py >>pythonoutput.md
          python3 datetimetest.py >>pythonoutput.md\
          python3 dictionary.py >>pythonoutput.md
          #python3 filehandling.py >>pythonoutput.md
          python3 forloop.py >>pythonoutput.md
          python3 functions.py >>pythonoutput.md
          python3 helloworld.py >>pythonoutput.md
          python3 ifelse.py >>pythonoutput.md
          #python3 interview.py >>pythonoutput.md
          python3 introduction.py >>pythonoutput.md
          #python3 iterator.py >>pythonoutput.md
          #python3 json.py >>pythonoutput.md
          #python3 lambda.py >>pythonoutput.md
          #python3 lists.py >>pythonoutput.md
          #python3 mathtest.py >>pythonoutput.md
          #python3 modules.py >>pythonoutput.md
          #python3 mongodb.py >>pythonoutput.md
          #python3 mysql.py >>pythonoutput.md
          python3 numbers.py >>pythonoutput.md
          python3 operators.py >>pythonoutput.md
          #python3 readdatajson.py >>pythonoutput.md
          #python3 regex.py >>pythonoutput.md
          #python3 sets.py >>pythonoutput.md
          python3 strings.py >>pythonoutput.md
          python3 syntax.py >>pythonoutput.md
          #python3 tryexcept.py >>pythonoutput.md
          #python3 tuples.py >>pythonoutput.md
          python3 variables.py >>pythonoutput.md
          python3 while.py >>pythonoutput.md
          git status
          git add . 
          git commit -m " Update output ."
          git push
          chmod +x singleexecution.sh
          chmod +x introduction.py
          sh ./singleexecution.sh
